### ISSUE TITLE
使用 Hexo-Git-Backup 插件备份你的 Hexo 博客 | TRHX'S BLOG

### ISSUE THREAD

**Issue by TRHX** [TRHX/TRHX.github.io#46]
https://www.itrhx.com/2019/09/29/A53-hexo-backup/ 

 一键备份博客数据，再也不怕数据丢失了！, 一个大学生用于自学的个人博客；主攻Python爬虫、WEB前端；求知若饥，虚心若愚；记录毕生所学！

**Comment by BlackFlame33** [comment]
大佬好！
针对备份的方法，如果使用这样的方法后，流程概括起来就是：先从本地备份到backup分支上，再将本地生成的静态文件上传到master分支上是吗？还是说其实是在一次部署的过程中又上传到backup分支备份又上传到master分支部署呢？

**Comment by TRHX** [comment]
> @BlackFlame33
> 大佬好！
> 针对备份的方法，如果使用这样的方法后，流程概括起来就是：先从本地备份到backup分支上，再将本地生成的静态文件上传到master分支上是吗？还是说其实是在一次部署的过程中又上传到backup分支备份又上传到master分支部署呢？

执行命令 `hexo b` 就会把本地源文件备份到 backup 分支上；
执行命令 `hexo g -d` 会把静态文件上传到 master 分支上
两者是分开的

**Comment by BlackFlame33** [comment]
原来是这样！但是虽然有备份但指令多起来了也很麻烦呢。。。大佬有考虑过官方文档的Travis脚本自动化部署吗？

发自我的iPhone

**Comment by TRHX** [comment]
> @BlackFlame33
> 原来是这样！但是虽然有备份但指令多起来了也很麻烦呢。。。大佬有考虑过官方文档的Travis脚本自动化部署吗？
> 
> 发自我的iPhone
> 
> > 在 2019年10月1日，下午1:32，Mr.Tan <notifications@github.com> 写道：
> > 
> > ﻿
> > @BlackFlame33
> > 大佬好！
> > 针对备份的方法，如果使用这样的方法后，流程概括起来就是：先从本地备份到backup分支上，再将本地生成的静态文件上传到master分支上是吗？还是说其实是在一次部署的过程中又上传到backup分支备份又上传到master分支部署呢？
> > 
> > 执行命令 hexo b 就会把本地源文件备份到 backup 分支上；
> > 执行命令 hexo g -d 会把静态文件上传到 master 分支上
> > 两者是分开的
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 

感觉就一个指令还好吧，不是很麻烦，其他的没有折腾过

**Comment by magicflung** [comment]
想问一下，备份到github，配置文件一些重要的参数会被人看见的吗，比如LeanCloud的keys

**Comment by TRHX** [comment]
> @magicflung
> 想问一下，备份到github，配置文件一些重要的参数会被人看见的吗，比如LeanCloud的keys

会的，因为你的根目录和主题目录的 config 配置文件也会备份到 github，像 LeanCloud 的 keys 是用做 Valine 评论系统的，而事实上这个 keys 可以直接在网页端看到，而像 hexo 这种静态托管的博客，这些参数看不看到都无所谓的啦，问题不大。

**Comment by wsqstar** [comment]
大佬，最后backup的时候，出现这个QAQ
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn rm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by TRHX** [comment]
> @wsqstar
> 大佬，最后backup的时候，出现这个QAQ
> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn rm ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
>     at onErrorNT (internal/child_process.js:407:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> Emitted 'error' event at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
>     at onErrorNT (internal/child_process.js:407:16)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

参考 https://github.com/coneycode/hexo-git-backup/issues/27

**Comment by Leming2021** [comment]
$ hexo b
INFO  Validating config
INFO  Start backup: git
On branch main
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   source/donate (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
error: src refspec master does not match any
error: failed to push some refs to 'github'
error: src refspec master does not match any
error: failed to push some refs to 'branch'
INFO  Backup done: git
大佬帮帮忙
